name: Nikita Ivochkin
description: This is my blog about learning programing and just about my life
external-image: false
picture: assets/images/avatar.jpg
resume: 'true'
resume-external: true
url: ''
permalink: '/:title/'
github: nikitaivochkin
facebook: nikita.ivochkin.7
vk: id195111736
linkedin: >-
  %D0%BD%D0%B8%D0%BA%D0%B8%D1%82%D0%B0-%D0%B8%D0%B2%D0%BE%D1%87%D0%BA%D0%B8%D0%BD-90a235178/
instagram: nikita__ivochkin/
lastfm: electricblow
email: nikita.ivochkin@icloud.com
authors:
  nikitaivochkin:
    name: Nikita Ivochkim
    external-image: true
    picture: assets/images/avatar.jpg
width: normal
about: true
blog: true
read-time: true
related: true
post-advance-links:
  - blog
show-author: 'true'
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
